Refactor
Teaching-projects/SZE-MOSZE-2020-Vodor pull request #11
Opened 2020-11-02 13:28 UTC by petinexus

@hegyhati refactorálás kész. A fájlok átnevezését git mv-vel csináltuk, de a history így is eltünt sajnos.

2020-11-03 09:36 UTC, hegyhati requested changes

2020-11-03 09:36 UTC, hegyhati commented on JSON.h
> +    }
ez igy nem lesz jo, ha T=int.

2020-11-03 09:36 UTC, hegyhati commented on Hero.cpp
> +			stod(returnedJSON.get<std::string>("cooldown_multiplier_per_level")));
na itt lenne a lenyeg, hogy ne kelljen stoizni get utan, hanem siman a get legyen hasznalva.

2020-11-03 14:22 UTC, rolandborbely commented
javítottuk, mostmár variantot használ minden map

2020-11-04 16:27 UTC, hegyhati approved these changes
Rendben. a sok `std::map<std::string,std::variant<std::string, int, double>> ` helyett lehet using-gal csinalni egy aliast. En most ezt beviszem, de egy minibranchen ha gondoljatok csinaljatok meg magatoknak, aztan vigyetek be a masterbe.

2020-11-04 16:27 UTC, merged