Game
Teaching-projects/SZE-MOSZE-2020-Vodor pull request #18
Opened 2020-11-25 18:23 UTC by petinexus

Mostantól a Game osztály felel a játék lebonyolitásáért.

2020-11-25 21:50 UTC, mesmatyi requested changes
szerintem rendben, ezenkívül még írtam egy ajánlást

2020-11-25 21:50 UTC, mesmatyi commented on Game.cpp
> +    }
a pálya elemeket esetlek tárolhatnátok az osztályban privát string-ként és u255x kódként, de ez inkább csak ajánlás

2020-11-26 11:50 UTC, rolandborbely commented
@mesmatyi készen van

2020-11-26 12:36 UTC, mesmatyi approved these changes

2020-11-26 12:55 UTC, Lazar-source approved these changes

2020-11-26 12:56 UTC, rolandborbely approved these changes

2020-11-26 12:56 UTC, merged